### ISSUE TITLE
[Bug]Typecho 1.2 Support

### ISSUE THREAD

**Issue by XenWayne** [wehaox/Typecho-Butterfly#3]
Typecho 1.2 rc.2
默认主题没有问题
切换到butterfly后报错Error establishing a database connection
开启debug后报错如下
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'views' in 'field list'
Typecho\Db\Adapter\SQLException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'views' in 'field list' in /www/wwwroot/beta.xenwayne.top/var/Typecho/Db/Adapter/Pdo.php:111
Stack trace:
#0 /www/wwwroot/beta.xenwayne.top/var/Typecho/Db.php(391): Typecho\Db\Adapter\Pdo-&gt;query()
#1 /www/wwwroot/beta.xenwayne.top/var/Typecho/Db.php(424): Typecho\Db-&gt;query()
#2 /www/wwwroot/beta.xenwayne.top/usr/themes/butterfly/functions.php(1320): Typecho\Db-&gt;fetchAll()
#3 /www/wwwroot/beta.xenwayne.top/usr/themes/butterfly/sidebar.php(210): theAllViews()
#4 /www/wwwroot/beta.xenwayne.top/var/Widget/Archive.php(1333): require('/www/wwwroot/be...')
#5 /www/wwwroot/beta.xenwayne.top/usr/themes/butterfly/index.php(104): Widget\Archive-&gt;need()
#6 /www/wwwroot/beta.xenwayne.top/var/Widget/Archive.php(1415): require_once('/www/wwwroot/be...')
#7 /www/wwwroot/beta.xenwayne.top/var/Typecho/Router.php(99): Widget\Archive-&gt;render()
#8 /www/wwwroot/beta.xenwayne.top/index.php(23): Typecho\Router::dispatch()
#9 {main}
```

sample:  https://beta.xenwayne.top
在得到reply前我会保留此站点。

**Comment by XenWayne** [comment]
Update:
很神奇（
开一次debug再关掉之后就一切正常了
离谱
在您主题评论区也看见过类似的情况
